function addDefsEquation(name) {
  const description = figure.add({
    name,
    make: 'equation',
    color: colorLight,
    // font: { family: 'TeXGyreTermes' },
    // textFont: { family: 'TeXGyreTermes', style: 'normal' },
    font: { family: 'Open Sans', width: 1.12, midAscent: 1.1, maxAscent: 1.5 },
    textFont: { family: 'Open Sans', style: 'normal', width: 1.12, midAscent: 1.1, maxAscent: 1.5 },
    scale: 4.7,
    position: [12, 1],
    formDefaults: { alignment: { xAlign: 'center' }, lazyLayout: true },
    mods: {
      scenarios: {
        default: { position: [12, 1] },
        top: { position: [12, 10.5] },
        highSmall: { position: [12.5, 5.5], scale: 1.4 },
        wave: { position: [12, 2.5], scale: 1.4 },
        definition: { position: [12, 10.5], scale: 1 },
      },
    },
    elements: {
      Transverse: { color: colorYellowText },
      Transverse_1: { color: colorYellowText },
      Wave: { color: colorYellowText },
      propDisturb: 'propogating disturbance',
      across: 'extend or direct across',
      colon: ': ',
      adjective: { text: 'adjective', style: 'italic' },
      long: { text: 'Longitudinal', color: colorYellowText },
      long1: { text: 'Longitudinal', color: colorYellowText, width: 1.1 },
      along: 'lengthwise or along',
      Single: { color: colorYellowText },
      Multiple: { color: colorYellowText },
      'Wave Equation': { color: colorYellowText },
      'Second Derivative: ': { color: colorYellowText },
    },
    forms: {
      waveDef: ['Wave', 'colon', 'propDisturb'],
      transverseWave: ['Transverse', '  ', 'Wave'],
      // transverseDef: ['Transverse', 'colon', 'across'],
      transverseDef: lines([
        ['Transverse', '  ', 'Wave'],
        scale(['Transverse_1', '_: ', '(adjective) extended or directed across'], 0.5),
      ], 0.8, 'center'),
      longWave: ['long', '  ', 'Wave'],
      longDef: lines([
        ['long', '  ', 'Wave'],
        scale(['long1', '_: ', '(adjective) placed or running lengthwise'], 0.5),
      ], 0.8, 'center'),
      ocean: ['Transverse', '_ and ', 'long', '_ '],
      // longWave: {
      //   content: ['long', '  ', 'Wave'],
      //   alignment: { yAlign: -0.4 },
      // },
      // longDef: {
      //   content: ['long', 'colon', 'along'],
      //   alignment: { yAlign: -0.4 },
      // },
      single1: ['Single', '  ', cont('', 4), '  ', cont('', 2.2)],
      single2: ['Single', '  ', cont('travelling', 3.9), '  ', cont('', 2.1)],
      single3: ['Single', '  ', cont('travelling', 3.9), '  ', cont('wave', 2.1)],
      multi: ['Multiple', ' ', cont('wave', 2), 's'],
      waveEqn: 'Wave Equation',
      waveEqn1: bc('Wave Equation', '(For one dimension)', '', 0.04, 0.04, 0.5),
      derivative1: scale(['Second Derivative: ', cont('', 5.5)], 0.7),
      derivative2: scale(['Second Derivative: ', cont('Shape or Curvature', 5.5)], 0.7),
      // initialSpace: ['Disturbance g(x) at an initial time'],
      // both: {
      //   lines: {
      //     content: [
      //       ['Disturbance g(x) at an initial time'],
      //       ['Disturbance h(t) at an initial position'],
      //     ],
      //     baselineSpace: 4,
      //   },
      // },
    },
  });
}